### ISSUE TITLE
ModuleNotFoundError: No module named 'OtterPlotter'

### ISSUE THREAD

**Issue by mssmison** [serycjon/otterplotter-scripts#1]
Hi,

 I'm interested in trying out some of your scripts here, but I'm not sure where to get the OtterPlotter module?

**Comment by serycjon** [comment]
Hi, the OtterPlotter module is not published. It just sends the drawing to my custom plotter, so you can safely delete all mentions of it and just use `export_svg` as shown in `scripts/hex_grids.py`.

**Comment by serycjon** [comment]
I have added a fallback on failed OtterPlotter import, so the scripts should work now.

(solved in 632d3caba3e9035e954c7e78b8c4daf8e0caa58b)
